# Generated by Django 4.2.24 on 2025-09-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingspot",
            name="profile_image_url",
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="terminal_pics/"),
        ),
    ]
