# Generated by Django 4.2.24 on 2025-09-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_parkingspot_profile_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkinglot",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="image_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="image_mime_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
