# Generated by Django 4.2.24 on 2025-09-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_parkinglot_profile_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingspot",
            name="image_url",
        ),
        migrations.AddField(
            model_name="parkingspot",
            name="image_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parkingspot",
            name="image_mime_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
