# Generated by Django 4.2.24 on 2025-10-01 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_parkingspothistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parkinglot",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="parkingspot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parkingspot",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="parkingspot",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="parkingspot",
            name="price_per_hour",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="parkingspot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="parkingspot",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("occupied", "Occupied"),
                    ("reserved", "Reserved"),
                    ("maintenance", "Maintenance"),
                ],
                default="available",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="parkingspothistory",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("occupied", "Occupied"),
                    ("reserved", "Reserved"),
                    ("maintenance", "Maintenance"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="parkingspothistory",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "Available"),
                    ("occupied", "Occupied"),
                    ("reserved", "Reserved"),
                    ("maintenance", "Maintenance"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spothistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("occupied", "Occupied"),
                    ("reserved", "Reserved"),
                    ("maintenance", "Maintenance"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="parkinglot",
            index=models.Index(
                fields=["latitude", "longitude"], name="core_parkin_latitud_a6f926_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parkinglot",
            index=models.Index(
                fields=["is_verified", "is_active"],
                name="core_parkin_is_veri_40ec11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parkinglot",
            index=models.Index(
                fields=["created_at"], name="core_parkin_created_34dea1_idx"
            ),
        ),
    ]
