# Generated by Django 4.2.24 on 2025-11-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reservation_notification_spotdetection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
